apiVersion: batch/v1
kind: Job
metadata:
  name: he-fides-serial
  namespace: ${HE_NAMESPACE}
  labels:
    app: he-fides-serial
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: he-fides-serial
    spec:
      restartPolicy: Never
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: hht-k8s-staging-22
      tolerations:
        - key: dedicated
          operator: Equal
          value: T4
          effect: NoSchedule
      containers:
        - name: fides-serial
          image: ${HE_FIDES_EXAMPLES_IMAGE}
          imagePullPolicy: Always
          workingDir: /tmp
          command:
            - /usr/local/bin/fides-serial
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: 12Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: temporary-files
          emptyDir:
            sizeLimit: 2Gi
