apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${HE_EVALUATE_API_PVC}
  namespace: ${HE_NAMESPACE}
  labels:
    app: he-evaluate-api-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${HE_EVALUATE_API_STORAGE}
