apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: counter-lab
  source:
    repoURL: git@gitlab.com:nhatcao99uetwork/k3s-demo-gitops.git
    targetRevision: main
    path: apps/counter/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: counter-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
