apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: he-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: he-lab
  source:
    repoURL: git@gitlab.com:nhatcao99uetwork/k3s-demo-gitops.git
    targetRevision: main
    path: apps/he/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: he-dev
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
