apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: he-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Homomorphic encryption GitLab CI and K3s development lab
  sourceRepos:
    - git@gitlab.com:nhatcao99uetwork/k3s-demo-gitops.git
  destinations:
    - namespace: he-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
