apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: counter-prod

resources:
  - ../../base

images:
  - name: registry.gitlab.com/nhatcao99uetwork/k3s-demo-app/api
    newTag: 49367a5c
  - name: registry.gitlab.com/nhatcao99uetwork/k3s-demo-app/web
    newTag: 49367a5c

patches:
  - target:
      kind: ConfigMap
      name: counter-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
  - target:
      kind: Deployment
      name: counter-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: counter-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: counter
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: counter-prod.k3s.test
